### ISSUE TITLE
请问下，您这套代码可以分享下么？

### ISSUE THREAD

**Issue by wenjiaer** [tianpeiyang/PTF_code#3]
深受这篇文章Efficient Deep Reinforcement Learning through Policy Transfer启发，奈何没有相应程序，请问下方便分享下代码么？

**Comment by yyds-xtt** [comment]
大佬不要着急，天培大佬说了12月份开源，12月份就能开源，各位大佬不要着急

**Comment by wenjiaer** [comment]
谢谢您的回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月10日(星期五) 上午10:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tianpeiyang/PTF_code] 请问下，您这套代码可以分享下么？ (Issue #3)





 
大佬不要着急，天培大佬说了12月份开源，12月份就能开源，各位大佬不要着急
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yyds-xtt** [comment]
大佬不要着急，天培大佬说了12月份开源，12月份就能开源，各位大佬不要着急

**Comment by yyds-xtt** [comment]
大佬不要着急，天培大佬说了12月份开源，12月份就能开源，各位大佬不要着急

**Comment by yyds-xtt** [comment]
该 开源了

**Comment by yyds-xtt** [comment]
该 开源了

**Comment by yyds-xtt** [comment]
该 开源了

**Comment by tianpeiyang** [comment]
Code has been released
